apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "java-spring-template.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "java-spring-template.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "java-spring-template.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
